version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: intra_postgres
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: intra_chat
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - intra-chat-docker

  ollama:
    image: ollama/ollama
    container_name: intra_ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    tty: true  # 避免 container 馬上結束
    networks:
      - intra-chat-docker

  qdrant:
    image: qdrant/qdrant
    container_name: intra_qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - intra-chat-docker

volumes:
  pg_data:
  qdrant_data:
  ollama_models:

networks:
  intra-chat-docker: