[project]
name = "intra-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "coloredlogs>=15.0.1",
    "fastapi>=0.115.14",
    "ollama>=0.5.1",
    "uvicorn>=0.34.3",
]
